apiVersion: batch/v1
kind: Job
metadata:
  name: loadgen-job
spec:
  template:
    spec:
      containers:
      - name: loadgen
        image: busybox
        command: [ "/bin/sh" ]
        args: [ "-c", "while true; do wget -q -O- http://example.com; done" ]
      restartPolicy: Never
  backoffLimit: 4
