apiVersion: v1
kind: Pod
metadata:
  name: testleap1
  labels:
        app: my-app
        environment: prod
spec:

containers:
- name: jnlp
  image: jenkinsaks01acr.azurecr.io/forge/jnlp:latest
  args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
- name: leap
  image: jenkinsaks01acr.azurecr.io/forge/leap:latest
  tty: true
  command:
  - cat

